### ISSUE TITLE
doze this work with Ubuntu 16.04 with apps name that have numbers or has a hyphens [-] in the app name

### ISSUE THREAD

**Issue by raykai** [krebbi/le-serverpilot#2]
doze this work with Ubuntu 16.04 with apps name that have numbers or has a hyphens [-] in the app name ?

you can see this post i did on the original work : https://github.com/dfinnema/le-serverpilot/issues/30

**Comment by krebbi** [comment]
yes, just tested it on a fresh 16.04 vultr server a few minutes ago.
